name: Build & Deploy PHP App to Lightsail

on:
  push:
    branches:
      - main  # Triggers after merge into main

jobs:
  build:
    name: Build PHP App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # Optional: If your app uses frontend build tools like npm
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      # - name: Build frontend assets
      #   run: |
      #     npm ci
      #     npm run build

      - name: Archive production build
        run: |
          zip -r build.zip . -x ".git/*" "tests/*" "node_modules/*"

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: php-app-build
          path: build.zip

  deploy:
    name: Deploy to AWS Lightsail
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: php-app-build

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/lightsail_key.pem
          chmod 600 ~/.ssh/lightsail_key.pem

      - name: Transfer and deploy
        run: |
          scp -i ~/.ssh/lightsail_key.pem -o StrictHostKeyChecking=no build.zip ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:/tmp/
          
          ssh -i ~/.ssh/lightsail_key.pem -o StrictHostKeyChecking=no ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            cd /var/www/html
            sudo rm -rf *
            sudo unzip /tmp/build.zip -d .
            sudo systemctl restart apache2
          EOF
