name: Build & Deploy PHP App to Lightsail

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build PHP App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

     

      - name: Archive production build
        run: |
          zip -r build.zip . -x ".git/*" "tests/*" "node_modules/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-app-build
          path: build.zip

  deploy:
    name: Deploy to AWS Lightsail
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo (required for artifact v4)
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: php-app-build
          path: .

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/lightsail_key.pem
          chmod 600 ~/.ssh/lightsail_key.pem

      - name: Deploy via SSH and unzip
        run: |
          scp -i ~/.ssh/lightsail_key.pem -o StrictHostKeyChecking=no build.zip ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:/tmp/

          ssh -i ~/.ssh/lightsail_key.pem -o StrictHostKeyChecking=no ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            cd /opt/bitnami/apache2/htdocs || exit 1
            sudo rm -rf *
            sudo unzip /tmp/build.zip -d .
            sudo /opt/bitnami/ctlscript.sh restart apache
          EOF
